# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Gullion
email: kgullion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science Student at the University of Cincinnati
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kylegullion.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
github_username:  kgullion
facebook_username: kylegullion

# Address information
address_street: 621 McAlpin Ave
address_city: Cincinnati
address_state: OH
address_zip: 45220

# Build settings
markdown: kramdown
